In [1]:
# Numpy 기본

In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.array([1,2,3,4]).reshape([2,2])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1,2,3,4]).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [9]:
np.ones((2,2)) # 1로 구성된 2x2 행렬

array([[1., 1.],
       [1., 1.]])

In [10]:
array = np.array([[1,2,3],[4,5,6]])

In [11]:
array[0]

array([1, 2, 3])

In [12]:
array[1]

array([4, 5, 6])

In [13]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array[1][1]

5

In [15]:
array[1,1] # row indx, col index

5

In [16]:
array[0, :2]

array([1, 2])

In [17]:
array[1, -1]

6

In [18]:
array[1, :]

array([4, 5, 6])

In [19]:
array.ndim

2

In [20]:
array.shape

(2, 3)

In [21]:
array.dtype

dtype('int32')

In [22]:
array.sum()

21

In [23]:
array.std()

1.707825127659933

In [24]:
array.var()

2.9166666666666665

In [25]:
array.view()

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
array.max()

6

In [27]:
nums = np.array([1,2,2,3])

In [28]:
set(nums) # set 은 중복을 허용하지 않음

{1, 2, 3}

In [29]:
np.unique(nums)

array([1, 2, 3])

In [30]:
len(nums)

4

In [31]:
nums

array([1, 2, 2, 3])

In [32]:
len(np.unique(nums))

3

In [33]:
np.arange(3,8,2) # 3 ~ 8 까지 2씩 증가한다.

array([3, 5, 7])

In [34]:
for i in np.arange(3,8,2) :
    print(i)

3
5
7


In [35]:
np.arange(start = 5, stop = 20, step = 5)

array([ 5, 10, 15])

In [36]:
nums
np.where(nums == 2, "okay", "no") # true 면 okay, false 면 no

array(['no', 'okay', 'okay', 'no'], dtype='<U4')